<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1"><!-- Begin Jekyll SEO tag v2.5.0 -->
<title>Python’s Unittest not seeing the exception from other threads | Konpat’s Record of Struggles</title>
<meta name="generator" content="Jekyll v3.8.5" />
<meta property="og:title" content="Python’s Unittest not seeing the exception from other threads" />
<meta name="author" content="Konpat Preechakul" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="I don’t know if using many threads for testing is a good practice or not. However, I do use it, and I do suffer the consequences from it. Python’s Unittest library will not heed whatever exception thrown from other threads than the main thread it running on! This will definitely cause problems especially when exceptions happen and your tests are still quite green, that cannot be good. One way to mitigate this problem is to create a GlobalExceptionWatcher that will see any exception thrown from any thread. The implementation I found over the internet was kinda hack, yet using with cautions it worked! It goes… class GlobalExceptionWatcher(object): import threading import os &#39;&#39;&#39; NOTE: It changes the behavior of &#39;threading&#39; module, which should be use in only limited area on a limited run &#39;&#39;&#39; def _store_excepthook(self): &#39;&#39;&#39; Uses as an exception handlers which stores any uncaught exceptions. &#39;&#39;&#39; formated_exc = self.__org_hook() self._exceptions.append(formated_exc) return formated_exc def start(self): &#39;&#39;&#39; Register us to the hook. &#39;&#39;&#39; self._exceptions = [] self.__org_hook = self.threading._format_exc self.threading._format_exc = self._store_excepthook def stop(self): &#39;&#39;&#39; Remove us from the hook, assure no exception were thrown. &#39;&#39;&#39; self.threading._format_exc = self.__org_hook if len(self._exceptions) != 0: tracebacks = self.os.linesep.join(self._exceptions) raise Exception(&#39;Exceptions in other threads: %s&#39; % tracebacks) def __enter__(self): self.start() def __exit__(self, type, value, traceback): self.stop() You can now use: class ExceptionOnThreadTest(unittest.TestCase): def test_exception_on_thread(self): import threading def run(): import time time.sleep(0.1) raise Exception(&#39;just an exception&#39;) def watcher(): with GlobalExceptionWatcher(): t = threading.Thread(target=run) t.start() t.join() self.assertRaises(Exception, watcher) And it turned red beautifully…" />
<meta property="og:description" content="I don’t know if using many threads for testing is a good practice or not. However, I do use it, and I do suffer the consequences from it. Python’s Unittest library will not heed whatever exception thrown from other threads than the main thread it running on! This will definitely cause problems especially when exceptions happen and your tests are still quite green, that cannot be good. One way to mitigate this problem is to create a GlobalExceptionWatcher that will see any exception thrown from any thread. The implementation I found over the internet was kinda hack, yet using with cautions it worked! It goes… class GlobalExceptionWatcher(object): import threading import os &#39;&#39;&#39; NOTE: It changes the behavior of &#39;threading&#39; module, which should be use in only limited area on a limited run &#39;&#39;&#39; def _store_excepthook(self): &#39;&#39;&#39; Uses as an exception handlers which stores any uncaught exceptions. &#39;&#39;&#39; formated_exc = self.__org_hook() self._exceptions.append(formated_exc) return formated_exc def start(self): &#39;&#39;&#39; Register us to the hook. &#39;&#39;&#39; self._exceptions = [] self.__org_hook = self.threading._format_exc self.threading._format_exc = self._store_excepthook def stop(self): &#39;&#39;&#39; Remove us from the hook, assure no exception were thrown. &#39;&#39;&#39; self.threading._format_exc = self.__org_hook if len(self._exceptions) != 0: tracebacks = self.os.linesep.join(self._exceptions) raise Exception(&#39;Exceptions in other threads: %s&#39; % tracebacks) def __enter__(self): self.start() def __exit__(self, type, value, traceback): self.stop() You can now use: class ExceptionOnThreadTest(unittest.TestCase): def test_exception_on_thread(self): import threading def run(): import time time.sleep(0.1) raise Exception(&#39;just an exception&#39;) def watcher(): with GlobalExceptionWatcher(): t = threading.Thread(target=run) t.start() t.join() self.assertRaises(Exception, watcher) And it turned red beautifully…" />
<link rel="canonical" href="https://blog.konpat.me/dev/2016/08/03/pythons-unittest-library-will-not-see-the-exception-from-other-threads.html" />
<meta property="og:url" content="https://blog.konpat.me/dev/2016/08/03/pythons-unittest-library-will-not-see-the-exception-from-other-threads.html" />
<meta property="og:site_name" content="Konpat’s Record of Struggles" />
<meta property="og:type" content="article" />
<meta property="article:published_time" content="2016-08-03T08:51:55+07:00" />
<script type="application/ld+json">
{"description":"I don’t know if using many threads for testing is a good practice or not. However, I do use it, and I do suffer the consequences from it. Python’s Unittest library will not heed whatever exception thrown from other threads than the main thread it running on! This will definitely cause problems especially when exceptions happen and your tests are still quite green, that cannot be good. One way to mitigate this problem is to create a GlobalExceptionWatcher that will see any exception thrown from any thread. The implementation I found over the internet was kinda hack, yet using with cautions it worked! It goes… class GlobalExceptionWatcher(object): import threading import os &#39;&#39;&#39; NOTE: It changes the behavior of &#39;threading&#39; module, which should be use in only limited area on a limited run &#39;&#39;&#39; def _store_excepthook(self): &#39;&#39;&#39; Uses as an exception handlers which stores any uncaught exceptions. &#39;&#39;&#39; formated_exc = self.__org_hook() self._exceptions.append(formated_exc) return formated_exc def start(self): &#39;&#39;&#39; Register us to the hook. &#39;&#39;&#39; self._exceptions = [] self.__org_hook = self.threading._format_exc self.threading._format_exc = self._store_excepthook def stop(self): &#39;&#39;&#39; Remove us from the hook, assure no exception were thrown. &#39;&#39;&#39; self.threading._format_exc = self.__org_hook if len(self._exceptions) != 0: tracebacks = self.os.linesep.join(self._exceptions) raise Exception(&#39;Exceptions in other threads: %s&#39; % tracebacks) def __enter__(self): self.start() def __exit__(self, type, value, traceback): self.stop() You can now use: class ExceptionOnThreadTest(unittest.TestCase): def test_exception_on_thread(self): import threading def run(): import time time.sleep(0.1) raise Exception(&#39;just an exception&#39;) def watcher(): with GlobalExceptionWatcher(): t = threading.Thread(target=run) t.start() t.join() self.assertRaises(Exception, watcher) And it turned red beautifully…","author":{"@type":"Person","name":"Konpat Preechakul"},"@type":"BlogPosting","url":"https://blog.konpat.me/dev/2016/08/03/pythons-unittest-library-will-not-see-the-exception-from-other-threads.html","headline":"Python’s Unittest not seeing the exception from other threads","dateModified":"2016-08-03T08:51:55+07:00","datePublished":"2016-08-03T08:51:55+07:00","mainEntityOfPage":{"@type":"WebPage","@id":"https://blog.konpat.me/dev/2016/08/03/pythons-unittest-library-will-not-see-the-exception-from-other-threads.html"},"@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->
<link rel="stylesheet" href="/assets/css/style.css"><link type="application/atom+xml" rel="alternate" href="https://blog.konpat.me/feed.xml" title="Konpat's Record of Struggles" /><script async src="https://www.googletagmanager.com/gtag/js?id=UA-91416417-1"></script>
<script>
  window['ga-disable-UA-91416417-1'] = window.doNotTrack === "1" || navigator.doNotTrack === "1" || navigator.doNotTrack === "yes" || navigator.msDoNotTrack === "1";
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-91416417-1');
</script>
</head>
<body><header class="site-header">

  <div class="wrapper"><a class="site-title" rel="author" href="/">Konpat&#39;s Record of Struggles</a><nav class="site-nav">
        <input type="checkbox" id="nav-trigger" class="nav-trigger" />
        <label for="nav-trigger">
          <span class="menu-icon">
            <svg viewBox="0 0 18 15" width="18px" height="15px">
              <path d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.032C17.335,0,18,0.665,18,1.484L18,1.484z M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.032C17.335,6.031,18,6.696,18,7.516L18,7.516z M18,13.516C18,14.335,17.335,15,16.516,15H1.484 C0.665,15,0,14.335,0,13.516l0,0c0-0.82,0.665-1.483,1.484-1.483h15.032C17.335,12.031,18,12.695,18,13.516L18,13.516z"/>
            </svg>
          </span>
        </label>
        
        <div class="trigger">
          <!--
            my_page.autogen is populated by the pagination logic for all pages
                            that are automatically created by the gem. Check for non-existence to exclude pagination pages from site.pages iterators
          -->
          
            
          
            
            <a class="page-link" href="/about/">About</a>
            
          
            
          
            
            <a class="page-link" href="/tags/">Tags</a>
            
          
            
          
            
          
            
            <a class="page-link" href="/all/index.html">All Posts</a>
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
            <a class="page-link" href="/dev/index.html">Development</a>
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
            
          
        </div>
      </nav></div>
</header>
<main class="page-content" aria-label="Content">
      <div class="wrapper">
        <article class="post h-entry" itemscope itemtype="http://schema.org/BlogPosting">

  <header class="post-header">
    <h1 class="post-title p-name" itemprop="name headline">Python&#39;s Unittest not seeing the exception from other threads</h1>
    <p class="post-meta">
      <time class="dt-published" datetime="2016-08-03T08:51:55+07:00" itemprop="datePublished">Aug 3, 2016
      </time></p>
  </header>

  <div class="post-content e-content" itemprop="articleBody">
    <p>I don’t know if using many threads for testing is a good practice or not. However, I do use it, and I do suffer the consequences from it.</p>

<p>Python’s Unittest library <em>will not heed</em> whatever exception thrown from other threads than the main thread it running on!</p>

<p>This will definitely cause problems especially when exceptions happen and your tests are still quite <em>green</em>, that cannot be good.</p>

<p>One way to mitigate this problem is to create a <em>GlobalExceptionWatcher</em> that will see any exception thrown from any thread.</p>

<p>The implementation <strong>I found over the internet</strong> was kinda <em>hack</em>, yet using with cautions it worked!</p>

<p>It goes…</p>
<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">GlobalExceptionWatcher</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="kn">import</span> <span class="nn">threading</span>
    <span class="kn">import</span> <span class="nn">os</span>

    <span class="s">'''
    NOTE: It changes the behavior of 'threading' module, which should be use in only limited area on a limited run
    '''</span>

    <span class="k">def</span> <span class="nf">_store_excepthook</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="s">'''
        Uses as an exception handlers which stores any uncaught exceptions.
        '''</span>
        <span class="n">formated_exc</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">__org_hook</span><span class="p">()</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_exceptions</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">formated_exc</span><span class="p">)</span>
        <span class="k">return</span> <span class="n">formated_exc</span>

    <span class="k">def</span> <span class="nf">start</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="s">'''
        Register us to the hook.
        '''</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_exceptions</span> <span class="o">=</span> <span class="p">[]</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">__org_hook</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">threading</span><span class="o">.</span><span class="n">_format_exc</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">threading</span><span class="o">.</span><span class="n">_format_exc</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_store_excepthook</span>

    <span class="k">def</span> <span class="nf">stop</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="s">'''
        Remove us from the hook, assure no exception were thrown.
        '''</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">threading</span><span class="o">.</span><span class="n">_format_exc</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">__org_hook</span>
        <span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">_exceptions</span><span class="p">)</span> <span class="o">!=</span> <span class="mi">0</span><span class="p">:</span>
            <span class="n">tracebacks</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">os</span><span class="o">.</span><span class="n">linesep</span><span class="o">.</span><span class="n">join</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">_exceptions</span><span class="p">)</span>
            <span class="k">raise</span> <span class="nb">Exception</span><span class="p">(</span><span class="s">'Exceptions in other threads: </span><span class="si">%</span><span class="s">s'</span> <span class="o">%</span> <span class="n">tracebacks</span><span class="p">)</span>

    <span class="k">def</span> <span class="nf">__enter__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">start</span><span class="p">()</span>

    <span class="k">def</span> <span class="nf">__exit__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="nb">type</span><span class="p">,</span> <span class="n">value</span><span class="p">,</span> <span class="n">traceback</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">stop</span><span class="p">()</span>
</code></pre></div></div>

<p>You can now use:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">ExceptionOnThreadTest</span><span class="p">(</span><span class="n">unittest</span><span class="o">.</span><span class="n">TestCase</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">test_exception_on_thread</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="kn">import</span> <span class="nn">threading</span>

        <span class="k">def</span> <span class="nf">run</span><span class="p">():</span>
            <span class="kn">import</span> <span class="nn">time</span>
            <span class="n">time</span><span class="o">.</span><span class="n">sleep</span><span class="p">(</span><span class="mf">0.1</span><span class="p">)</span>
            <span class="k">raise</span> <span class="nb">Exception</span><span class="p">(</span><span class="s">'just an exception'</span><span class="p">)</span>

        <span class="k">def</span> <span class="nf">watcher</span><span class="p">():</span>
            <span class="k">with</span> <span class="n">GlobalExceptionWatcher</span><span class="p">():</span>
                <span class="n">t</span> <span class="o">=</span> <span class="n">threading</span><span class="o">.</span><span class="n">Thread</span><span class="p">(</span><span class="n">target</span><span class="o">=</span><span class="n">run</span><span class="p">)</span>
                <span class="n">t</span><span class="o">.</span><span class="n">start</span><span class="p">()</span>
                <span class="n">t</span><span class="o">.</span><span class="n">join</span><span class="p">()</span>

        <span class="bp">self</span><span class="o">.</span><span class="n">assertRaises</span><span class="p">(</span><span class="nb">Exception</span><span class="p">,</span> <span class="n">watcher</span><span class="p">)</span>
</code></pre></div></div>

<p>And it turned <em>red</em> beautifully…</p>


    <small>
      
      <a href="/tags/#python">python</a>
      
    </small>
  </div><a class="u-url" href="/dev/2016/08/03/pythons-unittest-library-will-not-see-the-exception-from-other-threads.html" hidden></a>
</article>

      </div>
    </main><footer class="site-footer h-card">
  <data class="u-url" href="/"></data>

  <div class="wrapper">

    <div class="footer-col-wrapper">
      <div class="footer-col one-half">
      <h2 class="footer-heading">Konpat&#39;s Record of Struggles</h2>
        <ul class="contact-list">
          <li class="p-name">Konpat Preechakul</li><li><a class="u-email" href="mailto:the.akita.ta@gmail.com">the.akita.ta@gmail.com</a></li></ul>
      </div>

      <div class="footer-col one-half">
        <p>O thou, I long to rival thy greatest invention, the mind.</p>
      </div>

      <div class="social-links"><ul class="social-media-list"><li><a href="https://www.facebook.com/phizaz" title="phizaz"><svg class="svg-icon grey"><use xlink:href="/assets/minima-social-icons.svg#facebook"></use></svg></a></li><li><a href="https://github.com/phizaz" title="phizaz"><svg class="svg-icon grey"><use xlink:href="/assets/minima-social-icons.svg#github"></use></svg></a></li><li><a href="https://www.instagram.com/phizaz" title="phizaz"><svg class="svg-icon grey"><use xlink:href="/assets/minima-social-icons.svg#instagram"></use></svg></a></li><li><a href="https://twitter.com/phizaz" title="phizaz"><svg class="svg-icon grey"><use xlink:href="/assets/minima-social-icons.svg#twitter"></use></svg></a></li><li><a href="/feed.xml" title="rss"><svg class="svg-icon grey"><use xlink:href="/assets/minima-social-icons.svg#rss"></use></svg></a></li></ul>
</div>
    </div>

  </div>

</footer>
</body>

</html>
